# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
#[character]      # The name of the module we are configuring is "character"
#symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[git_branch]
symbol = ""
truncation_length = "7"
truncation_symbol = ""

format = """\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    """
